#docker run -p 127.0.0.1:8080:8080 
# -e KC_BOOTSTRAP_ADMIN_USERNAME=<<KC_BOOTSTRAP_ADMIN_USERNAME>>
# -e KC_BOOTSTRAP_ADMIN_PASSWORD=<<KC_BOOTSTRAP_ADMIN_PASSWORD>>
# quay.io/keycloak/keycloak:26.5.5 start-dev

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: start-dev --import-realm
    volumes:
      - ./keycloak-config/realms:/opt/keycloak/data/import/
